[package]
name = "patui-plugin"
version = "0.1.0"
authors = ["Steven Trotter <stevetrot@gmail.com>"]
edition = "2021"
resolver = "2"

[lib]
name = "ptplugin"
crate-type = ["cdylib", "lib"]

[features]
default = ["macros"]

macros = ["patui-plugin-macros", "clap", "tracing-subscriber", "eyre"]
test = ["assert_cmd", "assertor", "escargot", "insta", "tracing-test"]

[dependencies]
patui-core = { path = "../patui-core" }
patui-plugin-macros = { path = "../patui-plugin-macros", optional = true }

async-stream = "0.3.6"
clap = { version = "4.5.23", features = ["cargo", "derive", "unicode", "string", "wrap_help"], optional = true }
convert_case = "0.6.0"
eyre = { version = "0.6.12", optional = true }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "time"] }
tokio-stream = "0.1.17"
tonic = "0.12.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"], optional = true }

assert_cmd = { version = "2.0.16", optional = true }
assertor = { version = "0.0.3", optional = true }
escargot = { version = "0.5.13", optional = true }
insta = { version = "1.41.1", optional = true }
tracing-test = { version = "0.2.5", optional = true }
chrono = "0.4.39"
