[package]
name = "patui-template"
version = "0.1.0"
authors = ["Steven Trotter <stevetrot@gmail.com>"]
edition = "2021"
resolver = "2"

[[bin]]
name = "patui-template"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.27", features = ["cargo", "derive", "unicode", "string", "wrap_help"] }
eyre = "0.6.12"
jaq-core = "2.0.0"
patui-plugin = { path = "../../patui-plugin" }
serde_json = "1.0.134"
tokio-stream = "0.1.17"
tonic = "0.12.3"
tokio = { version = "1.43.0", features = [ "macros", "rt-multi-thread", "time" ] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
async-stream = "0.3.6"

[dev-dependencies]
assertor = "0.0.3"
escargot = "0.5.13"
patui-plugin = { path = "../../patui-plugin", features = ["macros", "test"] }
tracing-test = "0.2.5"
